### ISSUE TITLE
New table: resources

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#28]
- table to store any resources such as documents and websites (only ever stores external URLs, no option to upload actual files)

##### Permissions by role

- public: none
- registered, no role: none
- analyst: R (where draft = false, ADDED 19/10/)
- manager: CRUD
- admin: CRUD

**Comment by tmfrnz** [comment]
#### fields

* title: text
* description: text
* url: string/text
* type_id: FK > resourcetypes.id
* private: boolean
* draft: boolean
* publication_date: datetime
* access_date: datetime
* status: text

**Comment by parndt** [comment]
Note: add `source_id` to `actors_measures` table per #20 to point a foreign key to this table

```
source_id: FK >resources.id
```

**Comment by parndt** [comment]
Note: add `has_many :resources` to `resourcetypes`

**Comment by parndt** [comment]
> Note: add `source_id` to `actors_measures` table per #20 to point a foreign key to this table
> 
> ```
> source_id: FK >resources.id
> ```

@tmfrnz is `source_id` required / not null?

**Comment by parndt** [comment]
> @tmfrnz is `source_id` required / not null?

@tmfrnz ^ ?

**Comment by tmfrnz** [comment]
> > @tmfrnz is `source_id` required / not null?
> 
> @tmfrnz ^ ?

sorry, not required =)

**Comment by tmfrnz** [comment]
migration now successful

**Comment by tmfrnz** [comment]
issue creating/editing: resource record is created/updated however a 500 error is returned:

```
2022-01-10T13:37:36.465744+00:00 heroku[router]: at=info method=PUT path="/resources/1" host=marine-defrag-api.herokuapp.com request_id=edeedad0-d97b-43bd-936a-75741e7c15cb fwd="77.20.250.121" dyno=web.1 connect=0ms service=124ms status=500 bytes=985 protocol=https
2022-01-10T13:37:36.344907+00:00 app[web.1]: I, [2022-01-10T13:37:36.344831 #4]  INFO -- : [edeedad0-d97b-43bd-936a-75741e7c15cb] Started PUT "/resources/1" for 77.20.250.121 at 2022-01-10 13:37:36 +0000
2022-01-10T13:37:36.346066+00:00 app[web.1]: I, [2022-01-10T13:37:36.345991 #4]  INFO -- : [edeedad0-d97b-43bd-936a-75741e7c15cb] Processing by ResourcesController#update as JSON
2022-01-10T13:37:36.346136+00:00 app[web.1]: I, [2022-01-10T13:37:36.346103 #4]  INFO -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   Parameters: {"draft"=>true, "publication_date"=>"2021-08-01T00:00:00.000+02:00", "private"=>true, "access_date"=>"2022-01-10T00:00:00.000+01:00", "created_at"=>"2022-01-10T13:50:26+01:00", "url"=>"https://resource.net", "resourcetype_id"=>1, "status"=>"", "updated_at"=>"2022-01-10T13:50:26+01:00", "title"=>"Reference 1a", "description"=>"description", "updated_by_id"=>1, "id"=>"1", "resource"=>{"title"=>"Reference 1a", "description"=>"description", "url"=>"https://resource.net", "resourcetype_id"=>1, "private"=>true, "draft"=>true, "publication_date"=>"2021-08-01T00:00:00.000+02:00", "access_date"=>"2022-01-10T00:00:00.000+01:00", "status"=>"", "updated_by_id"=>1, "created_at"=>"2022-01-10T13:50:26+01:00", "updated_at"=>"2022-01-10T13:50:26+01:00"}}
2022-01-10T13:37:36.346514+00:00 app[web.1]: W, [2022-01-10T13:37:36.346438 #4]  WARN -- : [edeedad0-d97b-43bd-936a-75741e7c15cb] Can't verify CSRF token authenticity.
2022-01-10T13:37:36.353797+00:00 app[web.1]: D, [2022-01-10T13:37:36.353716 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mUser Load (1.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "timo@dumpark.com"], ["LIMIT", 1]]
2022-01-10T13:37:36.360082+00:00 app[web.1]: D, [2022-01-10T13:37:36.359959 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mRole Exists? (3.9ms)[0m  [1m[34mSELECT 1 AS one FROM "roles" INNER JOIN "user_roles" ON "roles"."id" = "user_roles"."role_id" WHERE "user_roles"."user_id" = $1 AND "roles"."name" = $2 LIMIT $3[0m  [["user_id", 1], ["name", "admin"], ["LIMIT", 1]]
2022-01-10T13:37:36.361726+00:00 app[web.1]: D, [2022-01-10T13:37:36.361545 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mCACHE Role Exists? (0.0ms)[0m  [1m[34mSELECT 1 AS one FROM "roles" INNER JOIN "user_roles" ON "roles"."id" = "user_roles"."role_id" WHERE "user_roles"."user_id" = $1 AND "roles"."name" = $2 LIMIT $3[0m  [["user_id", 1], ["name", "admin"], ["LIMIT", 1]]
2022-01-10T13:37:36.368024+00:00 app[web.1]: D, [2022-01-10T13:37:36.367947 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mResource Load (3.6ms)[0m  [1m[34mSELECT "resources".* FROM "resources" WHERE "resources"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
2022-01-10T13:37:36.369551+00:00 app[web.1]: D, [2022-01-10T13:37:36.369474 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mCACHE Role Exists? (0.0ms)[0m  [1m[34mSELECT 1 AS one FROM "roles" INNER JOIN "user_roles" ON "roles"."id" = "user_roles"."role_id" WHERE "user_roles"."user_id" = $1 AND "roles"."name" = $2 LIMIT $3[0m  [["user_id", 1], ["name", "admin"], ["LIMIT", 1]]
2022-01-10T13:37:36.376017+00:00 app[web.1]: D, [2022-01-10T13:37:36.375928 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mTRANSACTION (4.4ms)[0m  [1m[35mBEGIN[0m
2022-01-10T13:37:36.384094+00:00 app[web.1]: D, [2022-01-10T13:37:36.384007 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mResourcetype Load (4.0ms)[0m  [1m[34mSELECT "resourcetypes".* FROM "resourcetypes" WHERE "resourcetypes"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
2022-01-10T13:37:36.392104+00:00 app[web.1]: D, [2022-01-10T13:37:36.392014 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mResource Update (5.8ms)[0m  [1m[33mUPDATE "resources" SET "title" = $1, "updated_at" = $2 WHERE "resources"."id" = $3[0m  [["title", "Reference 1a"], ["updated_at", "2022-01-10 13:37:36.384716"], ["id", 1]]
2022-01-10T13:37:36.400304+00:00 app[web.1]: D, [2022-01-10T13:37:36.400071 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mPaperTrail::Version Create (4.7ms)[0m  [1m[32mINSERT INTO "versions" ("item_type", "item_id", "event", "whodunnit", "object", "created_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["item_type", "Resource"], ["item_id", 1], ["event", "update"], ["whodunnit", "1"], ["object", "---\naccess_date: 2022-01-09 23:00:00.000000000 +00:00\ndescription: description\ndraft: true\nprivate: true\npublication_date: 2021-07-31 22:00:00.000000000 +00:00\nstatus: ''\ntitle: Reference 1\nresourcetype_id: 1\nurl: https://resource.net\nid: 1\ncreated_by_id: 1\nupdated_by_id: 1\ncreated_at: 2022-01-10 12:50:26.589031000 +00:00\nupdated_at: 2022-01-10 12:50:26.589031000 +00:00\n"], ["created_at", "2022-01-10 13:37:36.384716"]]
2022-01-10T13:37:36.408105+00:00 app[web.1]: D, [2022-01-10T13:37:36.408025 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[35m (6.4ms)[0m  [1m[34mSELECT COUNT(*) FROM "versions" WHERE "versions"."item_type" = $1 AND "versions"."item_id" = $2 AND "versions"."event" != $3[0m  [["item_type", "Resource"], ["item_id", 1], ["event", "create"]]
2022-01-10T13:37:36.420113+00:00 app[web.1]: D, [2022-01-10T13:37:36.420022 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mPaperTrail::Version Load (3.9ms)[0m  [1m[34mSELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."created_at" DESC, "versions"."id" DESC LIMIT $3[0m  [["item_id", 1], ["item_type", "Resource"], ["LIMIT", 1]]
2022-01-10T13:37:36.421372+00:00 app[web.1]: D, [2022-01-10T13:37:36.421296 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mCACHE PaperTrail::Version Load (0.0ms)[0m  [1m[34mSELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."created_at" DESC, "versions"."id" DESC LIMIT $3[0m  [["item_id", 1], ["item_type", "Resource"], ["LIMIT", 1]]
2022-01-10T13:37:36.428101+00:00 app[web.1]: D, [2022-01-10T13:37:36.428011 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mResource Update (5.9ms)[0m  [1m[33mUPDATE "resources" SET "updated_by_id" = $1 WHERE "resources"."id" = $2[0m  [["updated_by_id", 1], ["id", 1]]
2022-01-10T13:37:36.432077+00:00 app[web.1]: D, [2022-01-10T13:37:36.431976 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mTRANSACTION (3.7ms)[0m  [1m[35mCOMMIT[0m
2022-01-10T13:37:36.440102+00:00 app[web.1]: D, [2022-01-10T13:37:36.440018 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mResource Load (6.9ms)[0m  [1m[34mSELECT "resources".* FROM "resources" WHERE "resources"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
2022-01-10T13:37:36.448112+00:00 app[web.1]: D, [2022-01-10T13:37:36.448015 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mRole Exists? (6.4ms)[0m  [1m[34mSELECT 1 AS one FROM "roles" INNER JOIN "user_roles" ON "roles"."id" = "user_roles"."role_id" WHERE "user_roles"."user_id" = $1 AND "roles"."name" = $2 LIMIT $3[0m  [["user_id", 1], ["name", "admin"], ["LIMIT", 1]]
2022-01-10T13:37:36.452078+00:00 app[web.1]: D, [2022-01-10T13:37:36.452006 #4] DEBUG -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   [1m[36mResource Load (1.6ms)[0m  [1m[34mSELECT "resources".* FROM "resources" WHERE "resources"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
2022-01-10T13:37:36.462411+00:00 app[web.1]: I, [2022-01-10T13:37:36.462325 #4]  INFO -- : [edeedad0-d97b-43bd-936a-75741e7c15cb] Completed 500 Internal Server Error in 116ms (Views: 0.4ms | ActiveRecord: 62.7ms | Allocations: 8609)
2022-01-10T13:37:36.463991+00:00 app[web.1]: F, [2022-01-10T13:37:36.463919 #4] FATAL -- : [edeedad0-d97b-43bd-936a-75741e7c15cb]   
2022-01-10T13:37:36.463993+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] NoMethodError (undefined method `tokens' for #<Resource id: 1, title: "Reference 1a", description: "description", url: "https://resource.net", resourcetype_id: 1, private: true, draft: true, publication_date: "2021-08-01 00:00:00.000000000 +0200", access_date: "2022-01-10 00:00:00.000000000 +0100", status: "", created_by_id: 1, updated_by_id: 1, created_at: "2022-01-10 13:50:26.589031000 +0100", updated_at: "2022-01-10 14:37:36.384716000 +0100">):
2022-01-10T13:37:36.463994+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb]   
2022-01-10T13:37:36.463995+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activemodel (6.1.4.1) lib/active_model/attribute_methods.rb:469:in `method_missing'
2022-01-10T13:37:36.463996+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] devise_token_auth (1.2.0) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:106:in `update_auth_header'
2022-01-10T13:37:36.463996+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:427:in `block in make_lambda'
2022-01-10T13:37:36.463997+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:246:in `block in halting'
2022-01-10T13:37:36.463997+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:516:in `block in invoke_after'
2022-01-10T13:37:36.463998+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:516:in `each'
2022-01-10T13:37:36.463998+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:516:in `invoke_after'
2022-01-10T13:37:36.463999+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:131:in `block in run_callbacks'
2022-01-10T13:37:36.463999+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actiontext (6.1.4.1) lib/action_text/rendering.rb:20:in `with_renderer'
2022-01-10T13:37:36.464004+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actiontext (6.1.4.1) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
2022-01-10T13:37:36.464005+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:126:in `instance_exec'
2022-01-10T13:37:36.464005+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2022-01-10T13:37:36.464005+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
2022-01-10T13:37:36.464006+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
2022-01-10T13:37:36.464006+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
2022-01-10T13:37:36.464006+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
2022-01-10T13:37:36.464007+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/notifications.rb:203:in `block in instrument'
2022-01-10T13:37:36.464007+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2022-01-10T13:37:36.464007+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/notifications.rb:203:in `instrument'
2022-01-10T13:37:36.464008+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
2022-01-10T13:37:36.464008+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
2022-01-10T13:37:36.464008+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activerecord (6.1.4.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
2022-01-10T13:37:36.464009+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/abstract_controller/base.rb:165:in `process'
2022-01-10T13:37:36.464009+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionview (6.1.4.1) lib/action_view/rendering.rb:39:in `process'
2022-01-10T13:37:36.464009+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_controller/metal.rb:190:in `dispatch'
2022-01-10T13:37:36.464009+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_controller/metal.rb:254:in `dispatch'
2022-01-10T13:37:36.464010+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
2022-01-10T13:37:36.464010+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
2022-01-10T13:37:36.464014+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
2022-01-10T13:37:36.464015+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `each'
2022-01-10T13:37:36.464015+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `serve'
2022-01-10T13:37:36.464015+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
2022-01-10T13:37:36.464015+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] batch_api (0.3.0) lib/batch_api/rack_middleware.rb:18:in `call'
2022-01-10T13:37:36.464016+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
2022-01-10T13:37:36.464016+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
2022-01-10T13:37:36.464016+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] warden (1.2.9) lib/warden/manager.rb:34:in `call'
2022-01-10T13:37:36.464017+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
2022-01-10T13:37:36.464017+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack (2.2.3) lib/rack/etag.rb:27:in `call'
2022-01-10T13:37:36.464017+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
2022-01-10T13:37:36.464017+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack (2.2.3) lib/rack/head.rb:12:in `call'
2022-01-10T13:37:36.464017+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
2022-01-10T13:37:36.464018+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
2022-01-10T13:37:36.464018+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
2022-01-10T13:37:36.464018+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
2022-01-10T13:37:36.464018+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
2022-01-10T13:37:36.464019+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
2022-01-10T13:37:36.464019+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
2022-01-10T13:37:36.464019+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2022-01-10T13:37:36.464019+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
2022-01-10T13:37:36.464020+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
2022-01-10T13:37:36.464020+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
2022-01-10T13:37:36.464020+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] railties (6.1.4.1) lib/rails/rack/logger.rb:37:in `call_app'
2022-01-10T13:37:36.464020+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] railties (6.1.4.1) lib/rails/rack/logger.rb:26:in `block in call'
2022-01-10T13:37:36.464020+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
2022-01-10T13:37:36.464021+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:37:in `tagged'
2022-01-10T13:37:36.464021+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:99:in `tagged'
2022-01-10T13:37:36.464021+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] railties (6.1.4.1) lib/rails/rack/logger.rb:26:in `call'
2022-01-10T13:37:36.464021+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
2022-01-10T13:37:36.464021+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
2022-01-10T13:37:36.464022+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
2022-01-10T13:37:36.464022+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
2022-01-10T13:37:36.464022+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
2022-01-10T13:37:36.464023+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] activesupport (6.1.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2022-01-10T13:37:36.464023+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
2022-01-10T13:37:36.464023+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/static.rb:24:in `call'
2022-01-10T13:37:36.464026+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
2022-01-10T13:37:36.464026+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/ssl.rb:77:in `call'
2022-01-10T13:37:36.464026+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] actionpack (6.1.4.1) lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
2022-01-10T13:37:36.464027+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
2022-01-10T13:37:36.464027+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] secure_headers (6.3.3) lib/secure_headers/middleware.rb:11:in `call'
2022-01-10T13:37:36.464028+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] railties (6.1.4.1) lib/rails/engine.rb:539:in `call'
2022-01-10T13:37:36.464028+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] puma (5.5.2) lib/puma/configuration.rb:249:in `call'
2022-01-10T13:37:36.464028+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
2022-01-10T13:37:36.464029+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
2022-01-10T13:37:36.464029+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
2022-01-10T13:37:36.464030+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] puma (5.5.2) lib/puma/server.rb:447:in `process_client'
2022-01-10T13:37:36.464030+00:00 app[web.1]: [edeedad0-d97b-43bd-936a-75741e7c15cb] puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by tmfrnz** [comment]
I suspect that the word "resources" is already used in devise_token_auth

https://github.com/lynndylanhurley/devise_token_auth/blob/079d569668613f93001ff56d2c24429396d76440/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L106

**Comment by tmfrnz** [comment]
fixed by https://github.com/dumparkltd/marine-defrag-server/commit/791bc2fc4e830200ceb9bcffc269cc4fcbb9c9d1

@parndt: would be great if you could review and if needed improve that fix (likely there is a better/standard way of dealing with conflicts like this)

**Comment by parndt** [comment]
Your PR is great @tmfrnz  👏
