### ISSUE TITLE
Also need to delete references in join tables when deleting actors, actions, categories

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#76]
The following server error is triggered when attempting to delete items that are referenced in a join table
```
2021-11-10T23:24:51.100205+00:00 app[web.1]: I, [2021-11-10T23:24:51.100164 #4]  INFO -- : [61b906b7-e473-407b-b5eb-a90d6eebb713] Completed 500 Internal Server Error in 22ms (ActiveRecord: 10.7ms | Allocations: 3547)
2021-11-10T23:24:51.101123+00:00 app[web.1]: F, [2021-11-10T23:24:51.101079 #4] FATAL -- : [61b906b7-e473-407b-b5eb-a90d6eebb713]   
2021-11-10T23:24:51.101124+00:00 app[web.1]: [61b906b7-e473-407b-b5eb-a90d6eebb713] ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  update or delete on table "actors" violates foreign key constraint "fk_rails_0bc0294a5f" on table "actor_categories"
2021-11-10T23:24:51.101125+00:00 app[web.1]: DETAIL:  Key (id)=(11) is still referenced from table "actor_categories".
2021-11-10T23:24:51.101126+00:00 app[web.1]: ):
2021-11-10T23:24:51.101126+00:00 app[web.1]: [61b906b7-e473-407b-b5eb-a90d6eebb713]   
2021-11-10T23:24:51.101126+00:00 app[web.1]: [61b906b7-e473-407b-b5eb-a90d6eebb713] app/controllers/actors_controller.rb:45:in `destroy'
2021-11-10T23:24:51.102883+00:00 heroku[router]: at=info method=DELETE path="/actors/11" host=marine-defrag-api.herokuapp.com request_id=61b906b7-e473-407b-b5eb-a90d6eebb713 fwd="77.20.249.242" dyno=web.1 connect=0ms service=26ms status=500 bytes=985 protocol=https
```

We thus need to make sure we also destroy all references in the join tables, ie
- measure_categories
- measure_actors
- actor_categories
- actor_measures
- memberships
- user_categories

**Comment by tmfrnz** [comment]
I can confirm this now works, at least mostly =) 

I am getting an error, deleting a category that was associated with an actor 

```
2021-11-11T22:54:24.001693+00:00 app[web.1]: [28cf150e-f179-46b4-b99d-475c9fbdef6e] ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  update or delete on table "categories" violates foreign key constraint "fk_rails_1b2c961c10" on table "actor_categories"
2021-11-11T22:54:24.001694+00:00 app[web.1]: DETAIL:  Key (id)=(64) is still referenced from table "actor_categories".
2021-11-11T22:54:24.001695+00:00 app[web.1]: ):
2021-11-11T22:54:24.001696+00:00 app[web.1]: [28cf150e-f179-46b4-b99d-475c9fbdef6e]   
2021-11-11T22:54:24.001696+00:00 app[web.1]: [28cf150e-f179-46b4-b99d-475c9fbdef6e] app/controllers/categories_controller.rb:43:in `destroy'
2021-11-11T22:54:24.005552+00:00 heroku[router]: at=info method=DELETE path="/categories/64" host=marine-defrag-api.herokuapp.com request_id=28cf150e-f179-46b4-b99d-475c9fbdef6e fwd="77.20.249.242" dyno=web.1 connect=0ms service=47ms status=500 bytes=985 protocol=https
```

For a quick fix, I assume adding `has_many :actor_categories, inverse_of: :category, dependent: :destroy` to 
https://github.com/dumparkltd/marine-defrag-server/blob/master/app/models/category.rb 

Could do tomorrow but would leave the specs to you @parndt

**Comment by parndt** [comment]
thanks @tmfrnz for testing that

**Comment by tmfrnz** [comment]
@parndt well yes though should have really done so before approving the pr I guess =)

**Comment by tmfrnz** [comment]
Happy to confirm this now works
